package tableexample;

import javafx.application.Application;
import javafx.beans.property.*;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

import java.time.LocalDate;

public class Case1 extends Application {

    @Override
    public void start(Stage primaryStage) {
        BorderPane root = new BorderPane();
        primaryStage.setScene(new Scene(root, 300, 120));
        primaryStage.show();

        TableView<MyClass> tableView = new TableView<>();
        TableColumn<MyClass, Integer> column1 = new TableColumn<>("column1");
        TableColumn<MyClass, String> column2 = new TableColumn<>("column2");
        TableColumn<MyClass, LocalDate> column3 = new TableColumn<>("column3");
        column1.setCellValueFactory(new PropertyValueFactory<>("value1"));
        column2.setCellValueFactory(new PropertyValueFactory<>("value2"));
        column3.setCellValueFactory(new PropertyValueFactory<>("value3"));
        tableView.getColumns().addAll(column1, column2, column3);

        ObservableList<MyClass> data = FXCollections.observableArrayList();
        data.add(new MyClass(100, "text1", LocalDate.of(2017, 5, 5)));
        data.add(new MyClass(200, "text2", LocalDate.of(2017, 5, 6)));
        data.add(new MyClass(300, "text3", LocalDate.of(2017, 5, 7)));
        tableView.setItems(data);

        root.setCenter(tableView);
    }

    public class MyClass {
        private IntegerProperty value1;
        private StringProperty value2;
        private ObjectProperty<LocalDate> value3;

        public MyClass(Integer value1, String value2, LocalDate value3) {
            this.value1 = new SimpleIntegerProperty(value1);
            this.value2 = new SimpleStringProperty(value2);
            this.value3 = new SimpleObjectProperty<>(value3);
        }

        // ----- Generated by IntellJ IDEA -----
        public int getValue1() {return value1.get();}
        public IntegerProperty value1Property() {return value1;}
        public void setValue1(int value1) {this.value1.set(value1);}
        public String getValue2() {return value2.get();}
        public StringProperty value2Property() {return value2;}
        public void setValue2(String value2) {this.value2.set(value2);}
        public LocalDate getValue3() {return value3.get();}
        public ObjectProperty<LocalDate> value3Property() {return value3;}
        public void setValue3(LocalDate value3) {this.value3.set(value3);}
    }

    public static void main(String[] args) throws Exception {
        launch(args);

    }
}